// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMedecins():Promise<Array<main.Medecin>>;

export function GetPatients():Promise<Array<main.Patient>>;

export function GetRendezVous():Promise<Array<main.RendezVous>>;

export function Greet(arg1:string):Promise<string>;
