// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMedecin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function AddPatient(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function AddRendezVous(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function AnnulerRendezVous(arg1:number,arg2:string):Promise<string>;

export function DeleteConsultation(arg1:number):Promise<string>;

export function DeleteMedecin(arg1:string):Promise<string>;

export function DeletePatient(arg1:number):Promise<string>;

export function DeleteRendezVous(arg1:number):Promise<string>;

export function GetConsultationsByMedecin(arg1:string):Promise<Array<main.ConsultationDetail>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetMedecins():Promise<Array<main.Medecin>>;

export function GetPatients():Promise<Array<main.Patient>>;

export function GetRendezVous():Promise<Array<main.RendezVous>>;

export function GetToutesLesConsultations():Promise<Array<main.ConsultationDetail>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.Utilisateur>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function TerminerRendezVous(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateMedecin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UpdatePatient(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function UpdateRendezVous(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UpdateRendezVousStatut(arg1:number,arg2:string):Promise<string>;
