// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMedecins() {
  return window['go']['main']['App']['GetMedecins']();
}

export function GetPatients() {
  return window['go']['main']['App']['GetPatients']();
}

export function GetRendezVous() {
  return window['go']['main']['App']['GetRendezVous']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
