// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMedecin(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddMedecin'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddPatient(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddPatient'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddRendezVous(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRendezVous'](arg1, arg2, arg3, arg4, arg5);
}

export function AnnulerRendezVous(arg1, arg2) {
  return window['go']['main']['App']['AnnulerRendezVous'](arg1, arg2);
}

export function DeleteConsultation(arg1) {
  return window['go']['main']['App']['DeleteConsultation'](arg1);
}

export function DeleteMedecin(arg1) {
  return window['go']['main']['App']['DeleteMedecin'](arg1);
}

export function DeletePatient(arg1) {
  return window['go']['main']['App']['DeletePatient'](arg1);
}

export function DeleteRendezVous(arg1) {
  return window['go']['main']['App']['DeleteRendezVous'](arg1);
}

export function GetConsultationsByMedecin(arg1) {
  return window['go']['main']['App']['GetConsultationsByMedecin'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetMedecins() {
  return window['go']['main']['App']['GetMedecins']();
}

export function GetPatients() {
  return window['go']['main']['App']['GetPatients']();
}

export function GetRendezVous() {
  return window['go']['main']['App']['GetRendezVous']();
}

export function GetToutesLesConsultations() {
  return window['go']['main']['App']['GetToutesLesConsultations']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TerminerRendezVous(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TerminerRendezVous'](arg1, arg2, arg3, arg4);
}

export function UpdateConsultation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateConsultation'](arg1, arg2, arg3, arg4);
}

export function UpdateMedecin(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMedecin'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdatePatient(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdatePatient'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateRendezVous(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateRendezVous'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateRendezVousStatut(arg1, arg2) {
  return window['go']['main']['App']['UpdateRendezVousStatut'](arg1, arg2);
}
